# docker run -d --name vital-postgresql -e POSTGRESQL_ADMIN_PASSWORD=root -p 5432:5432 -v d:\DB\Postgresql:/var/lib/postgresql centos/postgresql-96-centos7

#Create Databases
CREATE DATABASE pyo_dev;
CREATE DATABASE pyo_prod;

#Create database service accounts
CREATE USER pyo_dev_user WITH PASSWORD 'PickYourOwn2018' LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE USER pyo_prod_user WITH PASSWORD 'PickYourOwn2018' LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


#Database permissions
REVOKE CONNECT ON DATABASE pyo_dev FROM PUBLIC;
GRANT CONNECT ON DATABASE pyo_dev TO pyo_dev_user;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pyo_dev_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pyo_dev_user;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pyo_dev_user;

REVOKE CONNECT ON DATABASE pyo_prod FROM PUBLIC;
GRANT CONNECT ON DATABASE pyo_prod TO pyo_prod_user;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pyo_prod_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pyo_prod_user;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pyo_prod_user;
